// AI 产品导航站 - 数据模型 + Mock 数据

export type PricingTier = "free" | "freemium" | "paid";

export interface Category {
  id: string;
  name: string;
  slug: string;
  emoji: string;
  desc: string;
  gradient: string;
}

export interface Tag {
  id: string;
  name: string;
  slug: string;
}

export interface Product {
  id: string;
  name: string;
  tagline: string;
  description: string;
  url: string;
  categoryId: string;
  tagIds: string[];
  pricing: PricingTier;
  upvotes: number;
  logoColor: string; // 卡片左侧色块
  logoInitial: string; // 卡片左上字母
  featured?: boolean;
  submittedBy?: string;
  submittedAt: string; // ISO
}

export interface Submission {
  id: string;
  productName: string;
  productUrl: string;
  categoryId: string;
  tagIds: string[];
  description: string;
  submitterName: string;
  submitterEmail: string;
  submittedAt: string;
}

// ===== 分类 =====
export const categories: Category[] = [
  {
    id: "cat-chat",
    name: "AI 对话助手",
    slug: "chat",
    emoji: "💬",
    desc: "通用对话、问答、写作陪伴",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-coding",
    name: "AI 编程",
    slug: "coding",
    emoji: "🧑‍💻",
    desc: "代码生成、补全、调试与 Agent",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-image",
    name: "AI 图像与设计",
    slug: "image",
    emoji: "🎨",
    desc: "文生图、图像编辑、品牌设计",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-video",
    name: "AI 视频",
    slug: "video",
    emoji: "🎬",
    desc: "视频生成、剪辑、字幕、数字人",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-office",
    name: "AI 办公",
    slug: "office",
    emoji: "📊",
    desc: "PPT、表格、文档、效率工具",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-agent",
    name: "AI Agent",
    slug: "agent",
    emoji: "🤖",
    desc: "自主任务执行、自动化工作流",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-audio",
    name: "AI 音频",
    slug: "audio",
    emoji: "🎵",
    desc: "语音合成、配音、音乐生成",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-marketing",
    name: "AI 营销",
    slug: "marketing",
    emoji: "📈",
    desc: "广告文案、SEO、社媒营销",
    gradient: "from-brand-400 to-brand-600",
  },
  {
    id: "cat-research",
    name: "AI 研究",
    slug: "research",
    emoji: "📚",
    desc: "文献检索、论文分析、学术辅助",
    gradient: "from-brand-400 to-brand-600",
  },
];

// ===== 标签 =====
export const tags: Tag[] = [
  { id: "tag-gpt", name: "GPT", slug: "gpt" },
  { id: "tag-claude", name: "Claude", slug: "claude" },
  { id: "tag-deepseek", name: "DeepSeek", slug: "deepseek" },
  { id: "tag-llama", name: "Llama", slug: "llama" },
  { id: "tag-midjourney", name: "Midjourney", slug: "midjourney" },
  { id: "tag-stable-diffusion", name: "Stable Diffusion", slug: "stable-diffusion" },
  { id: "tag-flux", name: "FLUX", slug: "flux" },
  { id: "tag-suno", name: "Suno", slug: "suno" },
  { id: "tag-runway", name: "Runway", slug: "runway" },
  { id: "tag-pika", name: "Pika", slug: "pika" },
  { id: "tag-open-source", name: "开源", slug: "open-source" },
  { id: "tag-zh", name: "中文友好", slug: "zh-friendly" },
  { id: "tag-ide", name: "IDE 插件", slug: "ide-plugin" },
  { id: "tag-cli", name: "命令行", slug: "cli" },
  { id: "tag-browser", name: "浏览器", slug: "browser" },
  { id: "tag-mobile", name: "移动端", slug: "mobile" },
  { id: "tag-enterprise", name: "企业级", slug: "enterprise" },
  { id: "tag-free", name: "免费可用", slug: "free" },
  { id: "tag-design", name: "设计师", slug: "designer" },
  { id: "tag-writer", name: "写作者", slug: "writer" },
  { id: "tag-copilot", name: "Copilot", slug: "copilot" },
  { id: "tag-search", name: "搜索引擎", slug: "search-engine" },
  { id: "tag-tts", name: "语音合成", slug: "tts" },
  { id: "tag-music", name: "音乐生成", slug: "music-gen" },
  { id: "tag-meeting", name: "会议", slug: "meeting" },
  { id: "tag-academic", name: "学术", slug: "academic" },
  { id: "tag-seo", name: "SEO", slug: "seo" },
  { id: "tag-no-code", name: "零代码", slug: "no-code" },
  { id: "tag-api", name: "API", slug: "api" },
  { id: "tag-framework", name: "框架", slug: "framework" },
  { id: "tag-local", name: "本地部署", slug: "local" },
  { id: "tag-design-tool", name: "设计工具", slug: "design-tool" },
  { id: "tag-ad", name: "广告营销", slug: "ad-marketing" },
  { id: "tag-rag", name: "RAG", slug: "rag" },
  { id: "tag-voice-clone", name: "语音克隆", slug: "voice-clone" },
];

// ===== 产品 =====
export const products: Product[] = [
  {
    id: "p-chatgpt",
    name: "ChatGPT",
    tagline: "OpenAI 出品，通用对话王者",
    description:
      "基于 GPT-4o 系列模型，支持文本、图片、语音、文件理解，可搭建自定义 GPT。多端同步，生态成熟。",
    url: "https://chat.openai.com",
    categoryId: "cat-chat",
    tagIds: ["tag-gpt", "tag-enterprise", "tag-mobile"],
    pricing: "freemium",
    upvotes: 1820,
    logoColor: "#10a37f",
    logoInitial: "C",
    featured: true,
    submittedBy: "官方",
    submittedAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "p-claude",
    name: "Claude",
    tagline: "Anthropic 出品，长上下文写作首选",
    description: "擅长长文档分析、代码、写作，质量稳。提供 Sonnet / Opus / Haiku 多个版本，企业级安全对齐。",
    url: "https://claude.ai",
    categoryId: "cat-chat",
    tagIds: ["tag-claude", "tag-enterprise", "tag-writer"],
    pricing: "freemium",
    upvotes: 1560,
    logoColor: "#cc785c",
    logoInitial: "Cl",
    featured: true,
    submittedBy: "官方",
    submittedAt: "2026-08-21T02:00:00.000Z",
  },
  {
    id: "p-deepseek",
    name: "DeepSeek",
    tagline: "国产开源之光，超高性价比",
    description:
      "DeepSeek-V3 / R1 系列，开源开放，API 价格 1 分钱/次。中文场景表现优异，支持联网搜索、深度思考。",
    url: "https://chat.deepseek.com",
    categoryId: "cat-chat",
    tagIds: ["tag-deepseek", "tag-open-source", "tag-zh", "tag-free"],
    pricing: "freemium",
    upvotes: 1980,
    logoColor: "#1d44d6",
    logoInitial: "DS",
    featured: true,
    submittedBy: "主公",
    submittedAt: "2026-08-21T08:00:00.000Z",
  },
  {
    id: "p-gemini",
    name: "Gemini",
    tagline: "Google 出品，多模态深入场景",
    description: "Gemini 2.5 系列，深度集成 Google 生态（搜索、Workspace、Android）。支持百万级上下文。",
    url: "https://gemini.google.com",
    categoryId: "cat-chat",
    tagIds: ["tag-enterprise", "tag-mobile"],
    pricing: "freemium",
    upvotes: 1240,
    logoColor: "#4285f4",
    logoInitial: "G",
    submittedBy: "社区",
    submittedAt: "2026-08-22T11:00:00.000Z",
  },
  {
    id: "p-cursor",
    name: "Cursor",
    tagline: "AI 优先的代码编辑器",
    description:
      "基于 VSCode 深度改造，融合 GPT-4 / Claude 模型，支持项目级代码理解、跨文件编辑、多行重构。",
    url: "https://cursor.com",
    categoryId: "cat-coding",
    tagIds: ["tag-gpt", "tag-claude", "tag-ide"],
    pricing: "freemium",
    upvotes: 2100,
    logoColor: "#7c3aed",
    logoInitial: "Cu",
    featured: true,
    submittedBy: "主公",
    submittedAt: "2026-08-19T05:30:00.000Z",
  },
  {
    id: "p-claude-code",
    name: "Claude Code",
    tagline: "Anthropic 官方 CLI，Agent 式编程",
    description: "终端里的编码搭档，能理解大型仓库、自主规划任务、执行命令、提交代码。",
    url: "https://docs.claude.com/en/docs/claude-code",
    categoryId: "cat-coding",
    tagIds: ["tag-claude", "tag-cli"],
    pricing: "paid",
    upvotes: 1450,
    logoColor: "#cc785c",
    logoInitial: "CC",
    submittedBy: "官方",
    submittedAt: "2026-08-18T13:20:00.000Z",
  },
  {
    id: "p-trae",
    name: "Trae",
    tagline: "字节出品的 AI IDE",
    description: "对标 Cursor，国内外模型可切换。中英文都友好，支持 Claude / GPT / DeepSeek / Doubao。",
    url: "https://trae.ai",
    categoryId: "cat-coding",
    tagIds: ["tag-claude", "tag-deepseek", "tag-ide", "tag-zh"],
    pricing: "free",
    upvotes: 1320,
    logoColor: "#5d8bff",
    logoInitial: "T",
    submittedBy: "主公",
    submittedAt: "2026-08-21T09:00:00.000Z",
  },
  {
    id: "p-windsurf",
    name: "Windsurf",
    tagline: "Codeium 出品的 AI IDE",
    description: "Cascade 代理能跨文件执行，深度 IDE 整合，免费额度大方。",
    url: "https://codeium.com/windsurf",
    categoryId: "cat-coding",
    tagIds: ["tag-ide", "tag-free"],
    pricing: "freemium",
    upvotes: 980,
    logoColor: "#09b66d",
    logoInitial: "W",
    submittedBy: "社区",
    submittedAt: "2026-08-17T07:00:00.000Z",
  },
  {
    id: "p-midjourney",
    name: "Midjourney",
    tagline: "图像质感的天花板",
    description: "v6 / v7 系列持续精进，质感与审美业内标杆。支持风格、构图、灯光细节控制。",
    url: "https://midjourney.com",
    categoryId: "cat-image",
    tagIds: ["tag-midjourney", "tag-design"],
    pricing: "paid",
    upvotes: 1760,
    logoColor: "#1a1a1a",
    logoInitial: "MJ",
    featured: true,
    submittedBy: "社区",
    submittedAt: "2026-08-15T22:30:00.000Z",
  },
  {
    id: "p-leonardo",
    name: "Leonardo.ai",
    tagline: "可控、可商用、设计师友好",
    description: "支持 Canvas 编辑、模型微调、风格锁定；适合游戏与品牌设计。免费额度慷慨。",
    url: "https://leonardo.ai",
    categoryId: "cat-image",
    tagIds: ["tag-stable-diffusion", "tag-flux", "tag-design", "tag-free"],
    pricing: "freemium",
    upvotes: 1320,
    logoColor: "#f97316",
    logoInitial: "L",
    submittedBy: "社区",
    submittedAt: "2026-08-16T14:00:00.000Z",
  },
  {
    id: "p-ideogram",
    name: "Ideogram",
    tagline: "文字渲染之王",
    description: "在图像内生成清晰可读的英文 / 中文字体，海报、Logo 设计利器。",
    url: "https://ideogram.ai",
    categoryId: "cat-image",
    tagIds: ["tag-design", "tag-free"],
    pricing: "freemium",
    upvotes: 860,
    logoColor: "#5b21b6",
    logoInitial: "Ig",
    submittedBy: "社区",
    submittedAt: "2026-08-16T16:00:00.000Z",
  },
  {
    id: "p-suno",
    name: "Suno",
    tagline: "人人都是音乐人",
    description: "输入提示词或歌词，自动谱曲演唱。多风格、多乐器，免费版可生成 2 首/日。",
    url: "https://suno.com",
    categoryId: "cat-video",
    tagIds: ["tag-suno", "tag-free"],
    pricing: "freemium",
    upvotes: 1430,
    logoColor: "#ff6b35",
    logoInitial: "S",
    submittedBy: "社区",
    submittedAt: "2026-08-14T03:00:00.000Z",
  },
  {
    id: "p-runway",
    name: "Runway",
    tagline: "好莱坞都在用的视频生成 / 剪辑",
    description: "Gen-3 / Gen-4 模型，文生视频、视频延长、动作笔刷、相机控制，专业级后期工具。",
    url: "https://runwayml.com",
    categoryId: "cat-video",
    tagIds: ["tag-runway"],
    pricing: "paid",
    upvotes: 1190,
    logoColor: "#00ff88",
    logoInitial: "Rw",
    submittedBy: "社区",
    submittedAt: "2026-08-13T20:00:00.000Z",
  },
  {
    id: "p-pika",
    name: "Pika",
    tagline: "几分钟生成一致角色短片",
    description: "Pika 2.x 支持图片转视频、风格化、镜头控制，创意短视频友好。",
    url: "https://pika.art",
    categoryId: "cat-video",
    tagIds: ["tag-pika", "tag-free"],
    pricing: "freemium",
    upvotes: 880,
    logoColor: "#7c5cff",
    logoInitial: "P",
    submittedBy: "社区",
    submittedAt: "2026-08-13T19:00:00.000Z",
  },
  {
    id: "p-gamma",
    name: "Gamma",
    tagline: "一键生成漂亮 PPT 与网页",
    description: "输入主题自动出漂亮演示文稿，可二次编辑，支持导出 PDF / PPT。",
    url: "https://gamma.app",
    categoryId: "cat-office",
    tagIds: ["tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 1480,
    logoColor: "#5b21b6",
    logoInitial: "γ",
    featured: true,
    submittedBy: "主公",
    submittedAt: "2026-08-19T11:00:00.000Z",
  },
  {
    id: "p-notion-ai",
    name: "Notion AI",
    tagline: "Notion 内置 AI，文档写作全程陪伴",
    description: "总结、扩写、翻译、头脑风暴，原生在 Notion 工作流中。",
    url: "https://notion.so/product/ai",
    categoryId: "cat-office",
    tagIds: ["tag-gpt", "tag-writer", "tag-enterprise"],
    pricing: "paid",
    upvotes: 1380,
    logoColor: "#000000",
    logoInitial: "N",
    submittedBy: "社区",
    submittedAt: "2026-08-18T09:00:00.000Z",
  },
  {
    id: "p-meeting",
    name: "通义听悟",
    tagline: "阿里出品的会议转录与分析",
    description: "实时转录、声纹识别、自动总结、待办提取。中文会议场景极佳。",
    url: "https://tingwu.aliyun.com",
    categoryId: "cat-office",
    tagIds: ["tag-zh", "tag-free"],
    pricing: "freemium",
    upvotes: 920,
    logoColor: "#ff6900",
    logoInitial: "听",
    submittedBy: "主公",
    submittedAt: "2026-08-17T15:00:00.000Z",
  },
  {
    id: "p-manus",
    name: "Manus",
    tagline: "通用 AI Agent，自主规划任务",
    description: "中国团队出品的通用 Agent，能理解复杂指令、自主拆解、调用工具完成端到端任务。",
    url: "https://manus.im",
    categoryId: "cat-agent",
    tagIds: ["tag-zh", "tag-browser", "tag-cli"],
    pricing: "freemium",
    upvotes: 1620,
    logoColor: "#1f2937",
    logoInitial: "Mn",
    featured: true,
    submittedBy: "主公",
    submittedAt: "2026-08-21T12:30:00.000Z",
  },
  {
    id: "p-devin",
    name: "Devin",
    tagline: "Cognition 出品的 AI 软件工程师",
    description: "自主执行长任务，包含编码、调试、PR、部署等软件开发全流程。",
    url: "https://devin.ai",
    categoryId: "cat-agent",
    tagIds: ["tag-cli", "tag-enterprise"],
    pricing: "paid",
    upvotes: 1150,
    logoColor: "#0ea5e9",
    logoInitial: "Dv",
    submittedBy: "社区",
    submittedAt: "2026-08-18T17:00:00.000Z",
  },
  {
    id: "p-coze",
    name: "Coze 扣子",
    tagline: "字节出品，零代码搭 Bot",
    description: "可视化编排 AI Bot / Agent，集成丰富插件与知识库，支持发布到飞书、抖音、微信公众号。",
    url: "https://coze.com",
    categoryId: "cat-agent",
    tagIds: ["tag-zh", "tag-free", "tag-browser"],
    pricing: "freemium",
    upvotes: 1010,
    logoColor: "#1e40af",
    logoInitial: "Cz",
    submittedBy: "主公",
    submittedAt: "2026-08-20T13:00:00.000Z",
  },

  // ===== AI 对话助手（新增）=====
  {
    id: "p-perplexity",
    name: "Perplexity",
    tagline: "AI 驱动的搜索引擎",
    description: "用大模型实时检索网页，给出带引用来源的准确答案。支持 Pro 搜索、追问、文件上传。",
    url: "https://www.perplexity.ai",
    categoryId: "cat-chat",
    tagIds: ["tag-search", "tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 1340,
    logoColor: "#20808d",
    logoInitial: "Px",
    submittedBy: "社区",
    submittedAt: "2026-08-22T06:00:00.000Z",
  },
  {
    id: "p-character-ai",
    name: "Character.AI",
    tagline: "创建 AI 角色并与之对话",
    description: "用户可自定义角色人设、性格、语气，与虚拟人物、名人、动漫角色聊天。",
    url: "https://character.ai",
    categoryId: "cat-chat",
    tagIds: ["tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 980,
    logoColor: "#1a1a1a",
    logoInitial: "CA",
    submittedBy: "社区",
    submittedAt: "2026-08-20T14:00:00.000Z",
  },
  {
    id: "p-phind",
    name: "Phind",
    tagline: "程序员专用的 AI 搜索",
    description: "面向开发者的智能搜索引擎，支持代码搜索、技术文档检索，提供 VS Code 插件。",
    url: "https://www.phind.com",
    categoryId: "cat-chat",
    tagIds: ["tag-search", "tag-ide", "tag-free"],
    pricing: "freemium",
    upvotes: 760,
    logoColor: "#1f2937",
    logoInitial: "Ph",
    submittedBy: "社区",
    submittedAt: "2026-08-19T10:00:00.000Z",
  },
  {
    id: "p-you-com",
    name: "You.com",
    tagline: "注重隐私的 AI 搜索",
    description: "基于 AI 的搜索引擎，提供个性化搜索体验，同时保持用户数据 100% 私密。",
    url: "https://you.com",
    categoryId: "cat-chat",
    tagIds: ["tag-search", "tag-free"],
    pricing: "freemium",
    upvotes: 680,
    logoColor: "#8b5cf6",
    logoInitial: "Y",
    submittedBy: "社区",
    submittedAt: "2026-08-18T08:00:00.000Z",
  },
  {
    id: "p-chatpdf",
    name: "ChatPDF",
    tagline: "与任何 PDF 对话",
    description: "上传 PDF 文件，AI 自动理解内容，支持提问、总结、引用原文段落。",
    url: "https://www.chatpdf.com",
    categoryId: "cat-chat",
    tagIds: ["tag-free", "tag-rag"],
    pricing: "freemium",
    upvotes: 720,
    logoColor: "#ff5722",
    logoInitial: "CP",
    submittedBy: "社区",
    submittedAt: "2026-08-17T12:00:00.000Z",
  },
  {
    id: "p-tiledesk",
    name: "Tiledesk",
    tagline: "开源 LLM 聊天机器人平台",
    description: "无代码可视化编排聊天机器人，支持多渠道发布，集成 LLM 与知识库。",
    url: "https://tiledesk.com",
    categoryId: "cat-chat",
    tagIds: ["tag-open-source", "tag-no-code"],
    pricing: "freemium",
    upvotes: 420,
    logoColor: "#1e88e5",
    logoInitial: "Td",
    submittedBy: "社区",
    submittedAt: "2026-08-16T09:00:00.000Z",
  },
  {
    id: "p-privategpt",
    name: "privateGPT",
    tagline: "离线与文档对话",
    description: "完全本地运行的 LLM 文档问答系统，无需联网，保障数据隐私安全。",
    url: "https://github.com/imartinez/privateGPT",
    categoryId: "cat-chat",
    tagIds: ["tag-open-source", "tag-local", "tag-rag"],
    pricing: "free",
    upvotes: 1100,
    logoColor: "#2563eb",
    logoInitial: "pG",
    submittedBy: "社区",
    submittedAt: "2026-08-15T15:00:00.000Z",
  },
  {
    id: "p-quivr",
    name: "Quivr",
    tagline: "你的 AI 第二大脑",
    description: "上传任意文件，用 LLM 和 Embedding 与文件对话。开源、可自定义模型。",
    url: "https://github.com/StanGirard/quivr",
    categoryId: "cat-chat",
    tagIds: ["tag-open-source", "tag-rag"],
    pricing: "freemium",
    upvotes: 950,
    logoColor: "#7c3aed",
    logoInitial: "Qv",
    submittedBy: "社区",
    submittedAt: "2026-08-14T11:00:00.000Z",
  },

  // ===== AI 编程（新增）=====
  {
    id: "p-copilot",
    name: "GitHub Copilot",
    tagline: "AI 配对编程先驱",
    description: "基于 OpenAI Codex，在 VS Code / JetBrains 中实时建议代码和函数。支持 Chat、PR 总结。",
    url: "https://github.com/features/copilot",
    categoryId: "cat-coding",
    tagIds: ["tag-copilot", "tag-ide", "tag-enterprise"],
    pricing: "paid",
    upvotes: 1680,
    logoColor: "#24292f",
    logoInitial: "Co",
    featured: true,
    submittedBy: "社区",
    submittedAt: "2026-08-22T08:00:00.000Z",
  },
  {
    id: "p-tabnine",
    name: "Tabnine",
    tagline: "隐私优先的代码补全",
    description: "支持整行和整函数补全，可本地部署模型，确保代码不外泄。",
    url: "https://www.tabnine.com",
    categoryId: "cat-coding",
    tagIds: ["tag-ide", "tag-local", "tag-enterprise"],
    pricing: "freemium",
    upvotes: 680,
    logoColor: "#ff6f00",
    logoInitial: "Tb",
    submittedBy: "社区",
    submittedAt: "2026-08-20T07:00:00.000Z",
  },
  {
    id: "p-coderabbit",
    name: "CodeRabbit",
    tagline: "AI 代码审查",
    description: "自动分析 PR，给出代码质量反馈、改进建议和安全检查。集成 GitHub / GitLab。",
    url: "https://coderabbit.ai",
    categoryId: "cat-coding",
    tagIds: ["tag-enterprise", "tag-api"],
    pricing: "freemium",
    upvotes: 540,
    logoColor: "#f97316",
    logoInitial: "CR",
    submittedBy: "社区",
    submittedAt: "2026-08-19T13:00:00.000Z",
  },
  {
    id: "p-ollama",
    name: "Ollama",
    tagline: "本地运行大模型",
    description: "一条命令在本地加载运行 Llama、Gemma、Qwen 等开源大模型，提供 API 接口。",
    url: "https://ollama.com",
    categoryId: "cat-coding",
    tagIds: ["tag-open-source", "tag-local", "tag-cli", "tag-api"],
    pricing: "free",
    upvotes: 1520,
    logoColor: "#000000",
    logoInitial: "Ol",
    submittedBy: "社区",
    submittedAt: "2026-08-21T10:00:00.000Z",
  },
  {
    id: "p-langchain",
    name: "LangChain",
    tagline: "LLM 应用开发框架",
    description: "Python / JS 双语言框架，提供链式调用、Agent、记忆、RAG 等完整工具链。",
    url: "https://langchain.com",
    categoryId: "cat-coding",
    tagIds: ["tag-open-source", "tag-framework", "tag-api"],
    pricing: "freemium",
    upvotes: 1240,
    logoColor: "#1c3c3c",
    logoInitial: "LC",
    submittedBy: "社区",
    submittedAt: "2026-08-20T09:00:00.000Z",
  },
  {
    id: "p-llamaindex",
    name: "LlamaIndex",
    tagline: "LLM 数据连接框架",
    description: "专注于将外部数据（文档、数据库、API）接入 LLM，构建 RAG 应用的核心框架。",
    url: "https://www.llamaindex.ai",
    categoryId: "cat-coding",
    tagIds: ["tag-open-source", "tag-framework", "tag-rag"],
    pricing: "freemium",
    upvotes: 880,
    logoColor: "#6366f1",
    logoInitial: "LI",
    submittedBy: "社区",
    submittedAt: "2026-08-19T15:00:00.000Z",
  },
  {
    id: "p-gpt4all",
    name: "GPT4All",
    tagline: "3GB 显存跑大模型",
    description: "开源本地 LLM 运行工具，支持在普通笔记本上运行 Llama 等模型，无需 GPU。",
    url: "https://github.com/nomic-ai/gpt4all",
    categoryId: "cat-coding",
    tagIds: ["tag-open-source", "tag-local"],
    pricing: "free",
    upvotes: 760,
    logoColor: "#059669",
    logoInitial: "GA",
    submittedBy: "社区",
    submittedAt: "2026-08-18T11:00:00.000Z",
  },
  {
    id: "p-metagpt",
    name: "MetaGPT",
    tagline: "多 Agent 软件开发框架",
    description: "输入一行需求，自动输出 PRD、设计、任务拆解和代码仓库。多角色 Agent 协作。",
    url: "https://github.com/geekan/MetaGPT",
    categoryId: "cat-coding",
    tagIds: ["tag-open-source", "tag-framework"],
    pricing: "free",
    upvotes: 640,
    logoColor: "#1e40af",
    logoInitial: "MG",
    submittedBy: "社区",
    submittedAt: "2026-08-17T16:00:00.000Z",
  },
  {
    id: "p-kilocode",
    name: "Kilo Code",
    tagline: "开源 VS Code AI 编程助手",
    description: "支持规划、构建和修复代码，在 VS Code 内深度集成，开源可自定义模型。",
    url: "https://kilocode.ai",
    categoryId: "cat-coding",
    tagIds: ["tag-open-source", "tag-ide"],
    pricing: "free",
    upvotes: 380,
    logoColor: "#0ea5e9",
    logoInitial: "KC",
    submittedBy: "社区",
    submittedAt: "2026-08-16T14:00:00.000Z",
  },
  {
    id: "p-codium",
    name: "CodiumAI",
    tagline: "AI 自动生成测试用例",
    description: "在 IDE 中自动分析代码逻辑，建议非平凡测试用例，提升代码覆盖率与信心。",
    url: "https://www.codium.ai",
    categoryId: "cat-coding",
    tagIds: ["tag-ide", "tag-enterprise"],
    pricing: "freemium",
    upvotes: 520,
    logoColor: "#7c3aed",
    logoInitial: "Cd",
    submittedBy: "社区",
    submittedAt: "2026-08-15T18:00:00.000Z",
  },
  {
    id: "p-amazon-q",
    name: "Amazon Q Developer",
    tagline: "AWS 出品的 AI 编程助手",
    description: "支持 VS Code / IntelliJ，提供代码建议、安全扫描、代码转换和 Agent 式编程。",
    url: "https://aws.amazon.com/q/developer/",
    categoryId: "cat-coding",
    tagIds: ["tag-ide", "tag-enterprise", "tag-cli"],
    pricing: "freemium",
    upvotes: 420,
    logoColor: "#ff9900",
    logoInitial: "AQ",
    submittedBy: "社区",
    submittedAt: "2026-08-14T20:00:00.000Z",
  },

  // ===== AI 图像与设计（新增）=====
  {
    id: "p-dalle",
    name: "DALL·E 3",
    tagline: "OpenAI 出品的文生图",
    description: "理解复杂提示词，图像细节丰富、文字渲染能力强。深度集成 ChatGPT。",
    url: "https://openai.com/dall-e-3/",
    categoryId: "cat-image",
    tagIds: ["tag-gpt", "tag-design"],
    pricing: "paid",
    upvotes: 1340,
    logoColor: "#10a37f",
    logoInitial: "DE",
    submittedBy: "社区",
    submittedAt: "2026-08-22T05:00:00.000Z",
  },
  {
    id: "p-stable-diffusion",
    name: "Stable Diffusion",
    tagline: "开源文生图标杆",
    description: "Stability AI 出品，可在本地 GPU 运行，社区生态庞大，海量模型可下载。",
    url: "https://stability.ai",
    categoryId: "cat-image",
    tagIds: ["tag-stable-diffusion", "tag-open-source", "tag-local"],
    pricing: "freemium",
    upvotes: 1620,
    logoColor: "#7c3aed",
    logoInitial: "SD",
    submittedBy: "社区",
    submittedAt: "2026-08-21T14:00:00.000Z",
  },
  {
    id: "p-canva",
    name: "Canva AI",
    tagline: "人人可用的 AI 设计平台",
    description: "文生图、魔法编辑、一键去背景、品牌套件。模板丰富，零门槛上手。",
    url: "https://www.canva.com",
    categoryId: "cat-image",
    tagIds: ["tag-design-tool", "tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 1180,
    logoColor: "#00c4cc",
    logoInitial: "Cv",
    submittedBy: "社区",
    submittedAt: "2026-08-20T11:00:00.000Z",
  },
  {
    id: "p-playground",
    name: "Playground AI",
    tagline: "免费在线 AI 图像创作",
    description: "支持文生图、图生图、风格控制，可用于社交配图、海报、Logo 等创作。",
    url: "https://playgroundai.com",
    categoryId: "cat-image",
    tagIds: ["tag-free", "tag-design"],
    pricing: "freemium",
    upvotes: 780,
    logoColor: "#6366f1",
    logoInitial: "Pg",
    submittedBy: "社区",
    submittedAt: "2026-08-19T14:00:00.000Z",
  },
  {
    id: "p-photoroom",
    name: "PhotoRoom",
    tagline: "AI 去背景与产品图",
    description: "一键去除背景、替换背景、生成产品场景图。电商卖家的图像利器。",
    url: "https://www.photoroom.com",
    categoryId: "cat-image",
    tagIds: ["tag-design-tool", "tag-mobile", "tag-free"],
    pricing: "freemium",
    upvotes: 860,
    logoColor: "#5b21b6",
    logoInitial: "PR",
    submittedBy: "社区",
    submittedAt: "2026-08-18T16:00:00.000Z",
  },
  {
    id: "p-lexica",
    name: "Lexica",
    tagline: "Stable Diffusion 搜索引擎",
    description: "搜索数百万张 AI 生成图像及其提示词，也可直接生成图片。",
    url: "https://lexica.art",
    categoryId: "cat-image",
    tagIds: ["tag-search", "tag-stable-diffusion"],
    pricing: "freemium",
    upvotes: 620,
    logoColor: "#1e293b",
    logoInitial: "Lx",
    submittedBy: "社区",
    submittedAt: "2026-08-17T13:00:00.000Z",
  },
  {
    id: "p-civitai",
    name: "Civitai",
    tagline: "AI 模型社区与分享",
    description: "全球最大的 Stable Diffusion 模型分享平台，海量 checkpoint、LoRA、Embedding。",
    url: "https://civitai.com",
    categoryId: "cat-image",
    tagIds: ["tag-stable-diffusion", "tag-open-source", "tag-free"],
    pricing: "freemium",
    upvotes: 920,
    logoColor: "#3b82f6",
    logoInitial: "Cv",
    submittedBy: "社区",
    submittedAt: "2026-08-16T17:00:00.000Z",
  },
  {
    id: "p-clipdrop",
    name: "ClipDrop",
    tagline: "AI 图像处理工具箱",
    description: "去背景、重打光、放大、清理、换天等一键操作，由 Stability AI 驱动。",
    url: "https://clipdrop.co",
    categoryId: "cat-image",
    tagIds: ["tag-design-tool", "tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 680,
    logoColor: "#0ea5e9",
    logoInitial: "Cl",
    submittedBy: "社区",
    submittedAt: "2026-08-15T20:00:00.000Z",
  },
  {
    id: "p-krea",
    name: "KREA",
    tagline: "实时 AI 图像探索",
    description: "实时生成、增强放大、风格迁移，探索数百万 AI 图像与提示词集合。",
    url: "https://www.krea.ai",
    categoryId: "cat-image",
    tagIds: ["tag-design", "tag-free"],
    pricing: "freemium",
    upvotes: 540,
    logoColor: "#1a1a1a",
    logoInitial: "Kr",
    submittedBy: "社区",
    submittedAt: "2026-08-14T22:00:00.000Z",
  },
  {
    id: "p-openart",
    name: "OpenArt",
    tagline: "搜索与生成 AI 艺术",
    description: "搜索千万级提示词，支持 Stable Diffusion、DALL·E 生成，内置图像编辑器。",
    url: "https://openart.ai",
    categoryId: "cat-image",
    tagIds: ["tag-stable-diffusion", "tag-free", "tag-search"],
    pricing: "freemium",
    upvotes: 480,
    logoColor: "#7c3aed",
    logoInitial: "OA",
    submittedBy: "社区",
    submittedAt: "2026-08-13T16:00:00.000Z",
  },
  {
    id: "p-brandmark",
    name: "Brandmark",
    tagline: "AI Logo 设计工具",
    description: "输入品牌名称，自动生成 Logo、名片、社交媒体全套视觉。",
    url: "https://brandmark.io",
    categoryId: "cat-image",
    tagIds: ["tag-design-tool"],
    pricing: "paid",
    upvotes: 420,
    logoColor: "#f59e0b",
    logoInitial: "Bm",
    submittedBy: "社区",
    submittedAt: "2026-08-12T18:00:00.000Z",
  },
  {
    id: "p-ms-designer",
    name: "Microsoft Designer",
    tagline: "微软出品的 AI 设计工具",
    description: "文生图、模板设计、一键去背景，深度集成 Microsoft 365 生态。",
    url: "https://designer.microsoft.com",
    categoryId: "cat-image",
    tagIds: ["tag-design-tool", "tag-free"],
    pricing: "freemium",
    upvotes: 560,
    logoColor: "#0078d4",
    logoInitial: "MD",
    submittedBy: "社区",
    submittedAt: "2026-08-11T14:00:00.000Z",
  },

  // ===== AI 视频（新增）=====
  {
    id: "p-synthesia",
    name: "Synthesia",
    tagline: "文字生成数字人视频",
    description: "输入脚本，选择 AI 虚拟人，几分钟生成多语言讲解视频。企业培训首选。",
    url: "https://www.synthesia.io",
    categoryId: "cat-video",
    tagIds: ["tag-enterprise"],
    pricing: "paid",
    upvotes: 880,
    logoColor: "#1a1a1a",
    logoInitial: "Sy",
    submittedBy: "社区",
    submittedAt: "2026-08-21T15:00:00.000Z",
  },
  {
    id: "p-did",
    name: "D-ID",
    tagline: "照片变说话数字人",
    description: "上传一张照片，生成会说话的数字人视频，支持多语言口型同步。",
    url: "https://www.d-id.com",
    categoryId: "cat-video",
    tagIds: ["tag-free"],
    pricing: "freemium",
    upvotes: 760,
    logoColor: "#1e293b",
    logoInitial: "DI",
    submittedBy: "社区",
    submittedAt: "2026-08-20T16:00:00.000Z",
  },
  {
    id: "p-kling",
    name: "Kling AI",
    tagline: "快手出品的 AI 视频生成",
    description: "文生视频、图生视频，画质高、动态自然。支持创意短片和风格化视频。",
    url: "https://app.klingai.com/global/",
    categoryId: "cat-video",
    tagIds: ["tag-zh", "tag-free"],
    pricing: "freemium",
    upvotes: 1020,
    logoColor: "#3b82f6",
    logoInitial: "Kl",
    submittedBy: "社区",
    submittedAt: "2026-08-22T07:00:00.000Z",
  },
  {
    id: "p-hourone",
    name: "Hour One",
    tagline: "AI 虚拟主持人",
    description: "自动生成虚拟主持人视频，支持多种语言和风格，适合企业营销与培训。",
    url: "https://hourone.ai",
    categoryId: "cat-video",
    tagIds: ["tag-enterprise"],
    pricing: "paid",
    upvotes: 480,
    logoColor: "#8b5cf6",
    logoInitial: "HO",
    submittedBy: "社区",
    submittedAt: "2026-08-19T18:00:00.000Z",
  },
  {
    id: "p-shortgen",
    name: "ShortVideoGen",
    tagline: "文字生成短视频",
    description: "输入文字提示，自动生成带音频的短视频，适合社媒快速出片。",
    url: "https://shortgen.video",
    categoryId: "cat-video",
    tagIds: ["tag-free"],
    pricing: "freemium",
    upvotes: 360,
    logoColor: "#f97316",
    logoInitial: "SV",
    submittedBy: "社区",
    submittedAt: "2026-08-18T19:00:00.000Z",
  },

  // ===== AI 音频（新分类）=====
  {
    id: "p-elevenlabs",
    name: "ElevenLabs",
    tagline: "超逼真 AI 语音合成",
    description: "业界领先的语音克隆与 TTS，支持 29 种语言、情感建模，可自定义声音。",
    url: "https://elevenlabs.io",
    categoryId: "cat-audio",
    tagIds: ["tag-tts", "tag-voice-clone", "tag-free"],
    pricing: "freemium",
    upvotes: 1340,
    logoColor: "#000000",
    logoInitial: "EL",
    featured: true,
    submittedBy: "社区",
    submittedAt: "2026-08-22T09:00:00.000Z",
  },
  {
    id: "p-murf",
    name: "Murf AI",
    tagline: "专业级 AI 配音平台",
    description: "120+ 种声音、20+ 种语言，支持时间轴编辑、音调控制，适合商业配音。",
    url: "https://murf.ai",
    categoryId: "cat-audio",
    tagIds: ["tag-tts", "tag-enterprise"],
    pricing: "freemium",
    upvotes: 720,
    logoColor: "#6366f1",
    logoInitial: "Mf",
    submittedBy: "社区",
    submittedAt: "2026-08-21T16:00:00.000Z",
  },
  {
    id: "p-playht",
    name: "Play.ht",
    tagline: "AI 语音生成与克隆",
    description: "800+ 种自然声音，支持实时 TTS、语音克隆、多语言播客生成。",
    url: "https://play.ht",
    categoryId: "cat-audio",
    tagIds: ["tag-tts", "tag-voice-clone", "tag-free"],
    pricing: "freemium",
    upvotes: 580,
    logoColor: "#1a1a1a",
    logoInitial: "PH",
    submittedBy: "社区",
    submittedAt: "2026-08-20T18:00:00.000Z",
  },
  {
    id: "p-aiva",
    name: "AIVA",
    tagline: "AI 作曲家",
    description: "专注于古典与电影配乐风格，可自定义情绪、节奏、乐器编排。",
    url: "https://www.aiva.ai",
    categoryId: "cat-audio",
    tagIds: ["tag-music"],
    pricing: "freemium",
    upvotes: 620,
    logoColor: "#1e293b",
    logoInitial: "AI",
    submittedBy: "社区",
    submittedAt: "2026-08-19T17:00:00.000Z",
  },
  {
    id: "p-mubert",
    name: "Mubert",
    tagline: "实时生成免版税音乐",
    description: "根据场景、情绪、时长实时生成音乐，适合内容创作者和开发者。",
    url: "https://www.mubert.com",
    categoryId: "cat-audio",
    tagIds: ["tag-music", "tag-free", "tag-api"],
    pricing: "freemium",
    upvotes: 540,
    logoColor: "#7c3aed",
    logoInitial: "Mb",
    submittedBy: "社区",
    submittedAt: "2026-08-18T15:00:00.000Z",
  },
  {
    id: "p-soundraw",
    name: "Soundraw",
    tagline: "可定制 AI 音乐生成",
    description: "根据心情和风格生成音乐，可编辑段落、调整节奏和乐器。",
    url: "https://soundraw.io",
    categoryId: "cat-audio",
    tagIds: ["tag-music"],
    pricing: "paid",
    upvotes: 460,
    logoColor: "#1a1a1a",
    logoInitial: "Sw",
    submittedBy: "社区",
    submittedAt: "2026-08-17T17:00:00.000Z",
  },
  {
    id: "p-beatoven",
    name: "Beatoven.ai",
    tagline: "情绪驱动的 AI 音乐",
    description: "根据视频内容自动匹配情绪生成背景音乐，适合短视频与播客创作者。",
    url: "https://www.beatoven.ai",
    categoryId: "cat-audio",
    tagIds: ["tag-music", "tag-free"],
    pricing: "freemium",
    upvotes: 380,
    logoColor: "#6366f1",
    logoInitial: "Bv",
    submittedBy: "社区",
    submittedAt: "2026-08-16T19:00:00.000Z",
  },
  {
    id: "p-descript",
    name: "Descript",
    tagline: "音频/视频编辑 + 语音克隆",
    description: "像编辑文档一样编辑音视频，支持 Overdub 语音克隆、自动转录、去口癖。",
    url: "https://www.descript.com",
    categoryId: "cat-audio",
    tagIds: ["tag-voice-clone", "tag-meeting"],
    pricing: "freemium",
    upvotes: 680,
    logoColor: "#0a0a0a",
    logoInitial: "Ds",
    submittedBy: "社区",
    submittedAt: "2026-08-15T16:00:00.000Z",
  },

  // ===== AI 办公（新增）=====
  {
    id: "p-jasper",
    name: "Jasper",
    tagline: "AI 营销文案生成器",
    description: "面向营销团队的 AI 写作平台，支持品牌语气、模板、多人协作、SEO 优化。",
    url: "https://www.jasper.ai",
    categoryId: "cat-office",
    tagIds: ["tag-writer", "tag-enterprise", "tag-seo"],
    pricing: "paid",
    upvotes: 880,
    logoColor: "#7c3aed",
    logoInitial: "Ja",
    submittedBy: "社区",
    submittedAt: "2026-08-21T12:00:00.000Z",
  },
  {
    id: "p-copyai",
    name: "copy.ai",
    tagline: "AI 营销内容生成",
    description: "一键生成广告文案、社媒内容、邮件营销、产品描述，支持多种语气风格。",
    url: "https://www.copy.ai",
    categoryId: "cat-office",
    tagIds: ["tag-writer", "tag-free", "tag-ad"],
    pricing: "freemium",
    upvotes: 760,
    logoColor: "#1a1a1a",
    logoInitial: "ca",
    submittedBy: "社区",
    submittedAt: "2026-08-20T13:00:00.000Z",
  },
  {
    id: "p-quillbot",
    name: "QuillBot",
    tagline: "AI 改写与润色工具",
    description: "支持改写、总结、语法检查、翻译，学生与写作者的日常助手。",
    url: "https://quillbot.com",
    categoryId: "cat-office",
    tagIds: ["tag-writer", "tag-free"],
    pricing: "freemium",
    upvotes: 920,
    logoColor: "#1e40af",
    logoInitial: "QB",
    submittedBy: "社区",
    submittedAt: "2026-08-19T11:00:00.000Z",
  },
  {
    id: "p-deepl-write",
    name: "DeepL Write",
    tagline: "AI 写作润色与改写",
    description: "DeepL 出品，支持英文和德文写作改进：语法修正、用词替换、语气调整。",
    url: "https://www.deepl.com/write",
    categoryId: "cat-office",
    tagIds: ["tag-writer", "tag-free"],
    pricing: "freemium",
    upvotes: 680,
    logoColor: "#0f2b46",
    logoInitial: "DW",
    submittedBy: "社区",
    submittedAt: "2026-08-18T14:00:00.000Z",
  },
  {
    id: "p-otter",
    name: "Otter.ai",
    tagline: "AI 会议转录与总结",
    description: "实时转录会议音频，自动生成摘要、提取行动项，支持多平台录音。",
    url: "https://otter.ai",
    categoryId: "cat-office",
    tagIds: ["tag-meeting", "tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 820,
    logoColor: "#1a56db",
    logoInitial: "Ot",
    submittedBy: "社区",
    submittedAt: "2026-08-17T10:00:00.000Z",
  },
  {
    id: "p-notebooklm",
    name: "NotebookLM",
    tagline: "Google 出品的 AI 笔记",
    description: "上传文档、链接、视频，AI 自动总结、生成笔记、回答提问，支持音频概述。",
    url: "https://notebooklm.google.com",
    categoryId: "cat-office",
    tagIds: ["tag-free", "tag-rag"],
    pricing: "free",
    upvotes: 1080,
    logoColor: "#4285f4",
    logoInitial: "NL",
    submittedBy: "社区",
    submittedAt: "2026-08-22T03:00:00.000Z",
  },
  {
    id: "p-taskade",
    name: "Taskade",
    tagline: "AI 驱动的项目协作",
    description: "集成任务管理、思维导图、AI Agent，支持自动化工作流和团队协作。",
    url: "https://www.taskade.com",
    categoryId: "cat-office",
    tagIds: ["tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 460,
    logoColor: "#ff5722",
    logoInitial: "Tk",
    submittedBy: "社区",
    submittedAt: "2026-08-16T12:00:00.000Z",
  },
  {
    id: "p-mem",
    name: "Mem",
    tagline: "AI 个性化工作空间",
    description: "自动整理笔记、关联信息、智能搜索，让笔记像有大脑一样工作。",
    url: "https://mem.ai",
    categoryId: "cat-office",
    tagIds: ["tag-free"],
    pricing: "freemium",
    upvotes: 420,
    logoColor: "#1a1a1a",
    logoInitial: "Mm",
    submittedBy: "社区",
    submittedAt: "2026-08-15T14:00:00.000Z",
  },
  {
    id: "p-slideswizard",
    name: "SlidesWizard",
    tagline: "AI 一键生成演示文稿",
    description: "输入主题，自动生成 PowerPoint 和 Google Slides 演示文稿，10 倍提速。",
    url: "https://slideswizard.io",
    categoryId: "cat-office",
    tagIds: ["tag-free"],
    pricing: "freemium",
    upvotes: 320,
    logoColor: "#6366f1",
    logoInitial: "SW",
    submittedBy: "社区",
    submittedAt: "2026-08-14T16:00:00.000Z",
  },

  // ===== AI Agent（新增）=====
  {
    id: "p-mindpal",
    name: "MindPal",
    tagline: "构建 AI 第二大脑",
    description: "搭建多 Agent 团队，编排工作流，让 AI 协作完成复杂任务。",
    url: "https://mindpal.space",
    categoryId: "cat-agent",
    tagIds: ["tag-no-code"],
    pricing: "freemium",
    upvotes: 380,
    logoColor: "#7c3aed",
    logoInitial: "MP",
    submittedBy: "社区",
    submittedAt: "2026-08-18T12:00:00.000Z",
  },
  {
    id: "p-mindstudio",
    name: "MindStudio",
    tagline: "可视化构建 AI Agent",
    description: "拖拽式构建 AI Agent，100+ 模板，无需编码，支持企业级部署。",
    url: "https://mindstudio.ai",
    categoryId: "cat-agent",
    tagIds: ["tag-no-code", "tag-enterprise"],
    pricing: "freemium",
    upvotes: 420,
    logoColor: "#1e293b",
    logoInitial: "MS",
    submittedBy: "社区",
    submittedAt: "2026-08-17T14:00:00.000Z",
  },
  {
    id: "p-brainsoup",
    name: "BrainSoup",
    tagline: "多 Agent 本地客户端",
    description: "多 Agent + 多 LLM 原生客户端，AI 可记忆、响应事件、使用工具、自主协作。",
    url: "https://www.nurgo-software.com/products/brainsoup",
    categoryId: "cat-agent",
    tagIds: ["tag-local"],
    pricing: "freemium",
    upvotes: 280,
    logoColor: "#2563eb",
    logoInitial: "BS",
    submittedBy: "社区",
    submittedAt: "2026-08-16T15:00:00.000Z",
  },
  {
    id: "p-marblism",
    name: "Marblism",
    tagline: "AI 数字员工",
    description: "为企业打造 AI 员工，自动执行重复性业务任务，集成工作流。",
    url: "https://marblism.com",
    categoryId: "cat-agent",
    tagIds: ["tag-enterprise", "tag-no-code"],
    pricing: "freemium",
    upvotes: 320,
    logoColor: "#0ea5e9",
    logoInitial: "Mr",
    submittedBy: "社区",
    submittedAt: "2026-08-15T17:00:00.000Z",
  },

  // ===== AI 营销（新分类）=====
  {
    id: "p-mutiny",
    name: "Mutiny",
    tagline: "AI 网站个性化",
    description: "根据访客行为实时调整网站内容，提升转化率，面向 B2B 企业。",
    url: "https://www.mutinyhq.com",
    categoryId: "cat-marketing",
    tagIds: ["tag-enterprise", "tag-ad"],
    pricing: "paid",
    upvotes: 380,
    logoColor: "#1e293b",
    logoInitial: "Mt",
    submittedBy: "社区",
    submittedAt: "2026-08-19T10:00:00.000Z",
  },
  {
    id: "p-phrasee",
    name: "Phrasee",
    tagline: "AI 营销文案优化",
    description: "自动生成品牌一致的广告文案、邮件标题，A/B 测试优化效果。",
    url: "https://www.phrasee.co",
    categoryId: "cat-marketing",
    tagIds: ["tag-ad", "tag-enterprise"],
    pricing: "paid",
    upvotes: 320,
    logoColor: "#7c3aed",
    logoInitial: "Ph",
    submittedBy: "社区",
    submittedAt: "2026-08-18T13:00:00.000Z",
  },
  {
    id: "p-marketmuse",
    name: "MarketMuse",
    tagline: "AI SEO 内容优化",
    description: "分析内容差距、生成主题集群、优化关键词策略，提升搜索排名。",
    url: "https://www.marketmuse.com",
    categoryId: "cat-marketing",
    tagIds: ["tag-seo", "tag-enterprise"],
    pricing: "paid",
    upvotes: 280,
    logoColor: "#2563eb",
    logoInitial: "MM",
    submittedBy: "社区",
    submittedAt: "2026-08-17T16:00:00.000Z",
  },
  {
    id: "p-chatfuel",
    name: "Chatfuel",
    tagline: "AI 聊天机器人营销",
    description: "在 Messenger、Instagram、WhatsApp 部署 AI 聊天机器人，自动获客与客服。",
    url: "https://www.chatfuel.com",
    categoryId: "cat-marketing",
    tagIds: ["tag-ad", "tag-no-code"],
    pricing: "freemium",
    upvotes: 420,
    logoColor: "#00b4d8",
    logoInitial: "Cf",
    submittedBy: "社区",
    submittedAt: "2026-08-16T13:00:00.000Z",
  },
  {
    id: "p-taplio",
    name: "Taplio",
    tagline: "AI LinkedIn 营销工具",
    description: "AI 生成 LinkedIn 帖子、管理互动、分析数据，一站式个人品牌增长。",
    url: "https://taplio.com",
    categoryId: "cat-marketing",
    tagIds: ["tag-ad"],
    pricing: "paid",
    upvotes: 360,
    logoColor: "#0a66c2",
    logoInitial: "Tp",
    submittedBy: "社区",
    submittedAt: "2026-08-15T11:00:00.000Z",
  },
  {
    id: "p-promptbase",
    name: "PromptBase",
    tagline: "提示词交易市场",
    description: "买卖 DALL·E、GPT、Midjourney、Stable Diffusion 等优质提示词。",
    url: "https://promptbase.com",
    categoryId: "cat-marketing",
    tagIds: ["tag-design"],
    pricing: "freemium",
    upvotes: 280,
    logoColor: "#1a1a1a",
    logoInitial: "PB",
    submittedBy: "社区",
    submittedAt: "2026-08-14T13:00:00.000Z",
  },

  // ===== AI 研究（新分类）=====
  {
    id: "p-elicit",
    name: "Elicit",
    tagline: "AI 文献综述助手",
    description: "用大模型自动检索、筛选、提取论文关键信息，加速文献综述流程。",
    url: "https://elicit.org",
    categoryId: "cat-research",
    tagIds: ["tag-academic", "tag-free"],
    pricing: "freemium",
    upvotes: 680,
    logoColor: "#1e293b",
    logoInitial: "El",
    submittedBy: "社区",
    submittedAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "p-consensus",
    name: "Consensus",
    tagline: "AI 学术搜索引擎",
    description: "在科学论文中搜索答案，用 AI 提取研究发现共识，适合循证决策。",
    url: "https://consensus.app",
    categoryId: "cat-research",
    tagIds: ["tag-academic", "tag-search", "tag-free"],
    pricing: "freemium",
    upvotes: 520,
    logoColor: "#0ea5e9",
    logoInitial: "Cs",
    submittedBy: "社区",
    submittedAt: "2026-08-19T12:00:00.000Z",
  },
  {
    id: "p-scispace",
    name: "SciSpace",
    tagline: "与科学论文对话",
    description: "上传论文 PDF，AI 帮你理解公式、提取数据、回答提问，支持文献搜索。",
    url: "https://scispace.com",
    categoryId: "cat-research",
    tagIds: ["tag-academic", "tag-rag", "tag-free"],
    pricing: "freemium",
    upvotes: 460,
    logoColor: "#7c3aed",
    logoInitial: "SS",
    submittedBy: "社区",
    submittedAt: "2026-08-18T17:00:00.000Z",
  },
  {
    id: "p-genei",
    name: "genei",
    tagline: "AI 学术论文总结",
    description: "几秒内总结学术论文，提取关键段落，节省 80% 研究时间。",
    url: "https://www.genei.io",
    categoryId: "cat-research",
    tagIds: ["tag-academic"],
    pricing: "freemium",
    upvotes: 320,
    logoColor: "#1a1a1a",
    logoInitial: "gn",
    submittedBy: "社区",
    submittedAt: "2026-08-17T11:00:00.000Z",
  },
  {
    id: "p-explainpaper",
    name: "Explainpaper",
    tagline: "AI 论文阅读助手",
    description: "上传论文，高亮不懂的段落，AI 自动解释。大幅提升论文阅读效率。",
    url: "https://www.explainpaper.com",
    categoryId: "cat-research",
    tagIds: ["tag-academic", "tag-free"],
    pricing: "freemium",
    upvotes: 280,
    logoColor: "#2563eb",
    logoInitial: "Ep",
    submittedBy: "社区",
    submittedAt: "2026-08-16T10:00:00.000Z",
  },
  {
    id: "p-mathos",
    name: "Mathos AI",
    tagline: "AI 数学解题器",
    description: "拍照或输入数学题，AI 自动解题并给出步骤解析，覆盖小学到大学。",
    url: "https://www.mathgptpro.com",
    categoryId: "cat-research",
    tagIds: ["tag-academic", "tag-free", "tag-mobile"],
    pricing: "freemium",
    upvotes: 420,
    logoColor: "#1e40af",
    logoInitial: "Mt",
    submittedBy: "社区",
    submittedAt: "2026-08-15T09:00:00.000Z",
  },
];

  // ===== 提交记录 =====
export const submissions: Submission[] = [];

// ===== 工具函数 =====
export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getCategoryById(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function getTagBySlug(slug: string): Tag | undefined {
  return tags.find((t) => t.slug === slug);
}

export function getTagById(id: string): Tag | undefined {
  return tags.find((t) => t.id === id);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getProductsByTag(tagId: string): Product[] {
  return products.filter((p) => p.tagIds.includes(tagId));
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}

export function getProductsSortedByUpvotes(): Product[] {
  return [...products].sort((a, b) => b.upvotes - a.upvotes);
}
